# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminhome.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adHome(object):
    def setupUi(self, adHome):
        adHome.setObjectName("adHome")
        adHome.resize(924, 618)
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        adHome.setFont(font)
        self.centralwidget = QtWidgets.QWidget(adHome)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_14.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_13.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_home = QtWidgets.QPushButton(self.frame_3)
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout.addWidget(self.btn_home)
        self.btn_event = QtWidgets.QPushButton(self.frame_3)
        self.btn_event.setObjectName("btn_event")
        self.verticalLayout.addWidget(self.btn_event)
        self.btn_note = QtWidgets.QPushButton(self.frame_3)
        self.btn_note.setObjectName("btn_note")
        self.verticalLayout.addWidget(self.btn_note)
        self.btn_chat = QtWidgets.QPushButton(self.frame_3)
        self.btn_chat.setObjectName("btn_chat")
        self.verticalLayout.addWidget(self.btn_chat)
        self.btn_tem = QtWidgets.QPushButton(self.frame_3)
        self.btn_tem.setObjectName("btn_tem")
        self.verticalLayout.addWidget(self.btn_tem)
        self.btn_mypro = QtWidgets.QPushButton(self.frame_3)
        self.btn_mypro.setObjectName("btn_mypro")
        self.verticalLayout.addWidget(self.btn_mypro)
        self.btn_attend = QtWidgets.QPushButton(self.frame_3)
        self.btn_attend.setObjectName("btn_attend")
        self.verticalLayout.addWidget(self.btn_attend)
        self.btn_edit = QtWidgets.QPushButton(self.frame_3)
        self.btn_edit.setObjectName("btn_edit")
        self.verticalLayout.addWidget(self.btn_edit)
        self.btn_exit = QtWidgets.QPushButton(self.frame_3)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        self.gridLayout_11.addWidget(self.frame_3, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.gridLayout_8.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout_5.addWidget(self.listWidget, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 368, 471))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.treeWidget = QtWidgets.QTreeWidget(self.scrollAreaWidgetContents)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.gridLayout_6.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 2, 2)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 741, 467))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.scrollAreaWidgetContents_2)
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        self.horizontalLayout_2.addWidget(self.treeWidget_2)
        self.listWidget_2 = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.horizontalLayout_2.addWidget(self.listWidget_2)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_10, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_11.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_11, 0, 1, 1, 1)
        self.gridLayout_14.addWidget(self.frame, 1, 0, 1, 1)
        adHome.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(adHome)
        self.statusbar.setObjectName("statusbar")
        adHome.setStatusBar(self.statusbar)

        self.retranslateUi(adHome)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(adHome)

    def retranslateUi(self, adHome):
        _translate = QtCore.QCoreApplication.translate
        adHome.setWindowTitle(_translate("Home", "Home"))
        self.btn_home.setText(_translate("Home", "Home"))
        self.btn_event.setText(_translate("Home", "Events"))
        self.btn_note.setText(_translate("Home", "Notification"))
        self.btn_chat.setText(_translate("Home", "Chat"))
        self.btn_tem.setText(_translate("Home", "Teams"))
        self.btn_mypro.setText(_translate("Home", "My Profile  "))
        self.btn_attend.setText(_translate("Home", "Attendance"))
        self.btn_edit.setText(_translate("Home", "Edit member"))
        self.btn_exit.setText(_translate("Home", "exit"))
        self.label.setText(_translate("Home", "ICPC Members"))
        self.label_3.setText(_translate("Home", "Found areas"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Home", "Python"))
        item = self.listWidget.item(1)
        item.setText(_translate("Home", "C++"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidget.headerItem().setText(0, _translate("Home", "Name"))
        self.treeWidget.headerItem().setText(1, _translate("Home", "Year"))
        self.treeWidget.headerItem().setText(2, _translate("Home", "Department"))
        self.treeWidget.headerItem().setText(3, _translate("Home", "Score"))
        self.treeWidget.headerItem().setText(4, _translate("Home", "working on"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Home", "nahom"))
        self.treeWidget.topLevelItem(0).setText(1, _translate("Home", "3"))
        self.treeWidget.topLevelItem(0).setText(2, _translate("Home", "cse"))
        self.treeWidget.topLevelItem(0).setText(3, _translate("Home", "322"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Home", "Tab 1"))
        self.treeWidget_2.headerItem().setText(0, _translate("Home", "Name"))
        self.treeWidget_2.headerItem().setText(1, _translate("Home", "Year"))
        self.treeWidget_2.headerItem().setText(2, _translate("Home", "Department"))
        self.treeWidget_2.headerItem().setText(3, _translate("Home", "Rating"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("Home", "Abel        w"))
        self.treeWidget_2.topLevelItem(0).setText(1, _translate("Home", "3"))
        self.treeWidget_2.topLevelItem(0).setText(2, _translate("Home", "software"))
        self.treeWidget_2.topLevelItem(0).setText(3, _translate("Home", "9"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("Home", "Python"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("Home", "Development Members             "))
        self.label_4.setText(_translate("Home", "Language"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Home", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    adHome = QtWidgets.QMainWindow()
    ui = Ui_adHome()
    ui.setupUi(adHome)
    adHome.show()
    sys.exit(app.exec_())
