# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signu.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sign(object):
    def setupUi(self, signup):
        signup.setObjectName("signup")
        signup.resize(1083, 853)
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        signup.setFont(font)
        self.centralwidget = QtWidgets.QWidget(signup)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_10.addWidget(self.checkBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_10, 9, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.usern_2 = QtWidgets.QLineEdit(self.frame)
        self.usern_2.setStyleSheet("background-color: white;\n"
"color: rgb(25, 28, 255);\n"
"border-radius: 40px;")
        self.usern_2.setObjectName("usern_2")
        self.horizontalLayout_3.addWidget(self.usern_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("")
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.usern = QtWidgets.QLineEdit(self.frame)
        self.usern.setStyleSheet("background-color: white;\n"
"color: rgb(24, 35, 255);\n"
"border-radius: 40px;")
        self.usern.setObjectName("usern")
        self.horizontalLayout_2.addWidget(self.usern)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.usern_3 = QtWidgets.QLineEdit(self.frame)
        self.usern_3.setStyleSheet("background-color: white;\n"
"color: rgb(25, 28, 255);\n"
"border-radius: 40px;")
        self.usern_3.setObjectName("usern_3")
        self.horizontalLayout_4.addWidget(self.usern_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.password_2 = QtWidgets.QLineEdit(self.frame)
        self.password_2.setStyleSheet("background-color: white;\n"
"color: rgb(25, 28, 255);\n"
"border-radius: 40px;")
        self.password_2.setObjectName("password_2")
        self.horizontalLayout_8.addWidget(self.password_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.password_3 = QtWidgets.QLineEdit(self.frame)
        self.password_3.setStyleSheet("background-color: white;\n"
"color: rgb(25, 28, 255);\n"
"border-radius: 40px;")
        self.password_3.setObjectName("password_3")
        self.horizontalLayout_15.addWidget(self.password_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_15, 6, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.contact = QtWidgets.QLineEdit(self.frame)
        self.contact.setStyleSheet("background-color: white;\n"
"color: rgb(25, 28, 255);\n"
"border-radius: 40px;")
        self.contact.setObjectName("contact")
        self.horizontalLayout.addWidget(self.contact)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.horizontalLayout_9.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_9, 8, 0, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_27.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_27.addWidget(self.pushButton_3)
        self.gridLayout_9.addLayout(self.horizontalLayout_27, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem8, 0, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.frame_5)
        self.horizontalLayout_12.addWidget(self.frame)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 0, 0, 1, 1)
        signup.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(signup)
        self.statusbar.setObjectName("statusbar")
        signup.setStatusBar(self.statusbar)

        self.retranslateUi(signup)
        QtCore.QMetaObject.connectSlotsByName(signup)

    def retranslateUi(self, signup):
        _translate = QtCore.QCoreApplication.translate
        signup.setWindowTitle(_translate("signup", "Sign up form"))
        self.label_10.setText(_translate("signup", "Position As"))
        self.checkBox.setText(_translate("signup", "Admin"))
        self.label_6.setText(_translate("signup", "Group"))
        self.comboBox.setItemText(0, _translate("signup", "Devlopment"))
        self.comboBox.setItemText(1, _translate("signup", "ICPC"))
        self.comboBox.setItemText(2, _translate("signup", "Data Scice"))
        self.comboBox.setItemText(3, _translate("signup", "Cyber"))
        self.comboBox.setItemText(4, _translate("signup", "Campacity Buiding"))
        self.label_2.setText(_translate("signup", " Name"))
        self.usern_2.setText(_translate("signup", "Name"))
        self.label.setText(_translate("signup", " Username"))
        self.usern.setText(_translate("signup", "Username"))
        self.label_5.setText(_translate("signup", " Contact"))
        self.usern_3.setText(_translate("signup", "Contact"))
        self.label_8.setText(_translate("signup", "Department"))
        self.password_2.setText(_translate("signup", "Department"))
        self.label_7.setText(_translate("signup", "Year "))
        self.comboBox_3.setItemText(0, _translate("signup", "1st year"))
        self.comboBox_3.setItemText(1, _translate("signup", "2nd Year"))
        self.comboBox_3.setItemText(2, _translate("signup", "3rd Year"))
        self.comboBox_3.setItemText(3, _translate("signup", "4th Year"))
        self.comboBox_3.setItemText(4, _translate("signup", "5th Year"))
        self.label_12.setText(_translate("signup", "Email"))
        self.password_3.setText(_translate("signup", "Email"))
        self.label_9.setText(_translate("signup", "Sex"))
        self.comboBox_2.setItemText(0, _translate("signup", "Male"))
        self.comboBox_2.setItemText(1, _translate("signup", "Female"))
        self.label_4.setText(_translate("signup", "Profile Image"))
        self.contact.setText(_translate("signup", "Img"))
        self.pushButton_2.setText(_translate("signup", "Browther"))
        self.pushButton.setText(_translate("signup", "Submit"))
        self.pushButton_3.setText(_translate("signup", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signup = QtWidgets.QMainWindow()
    ui = Ui_sign()
    ui.setupUi(signup)
    signup.show()
    sys.exit(app.exec_())
